
module.exports = {
  "Bank":10,
  "Steuerberater":20,
  "Rechtsanwalt":30,
  "Krankenkasse ":40,
  "Unternehmensberater":50,
  "Marketing / Werbung / PR":60,
  "Bürodienstleister":70,
  "Personaldienstleister":80,
  "Versicherungsmakler":90,
  "Finanzmakler":100,
  "Immobilienmakler":110,
  "IT-Dienstleister":120,
  "Krisenmanagement":130,
  "Einkaufsverbände":140,
  "Gebäudereinigung":150,
  "Energieberater":160,
  "Sonstige Dienstleister":170,
  "Gemeindeverwaltung (Gewerbeamt, Wirtschaftsförderung Stadt, Bauamt, usw.)":180,
  "Industrie- und Handelskammer":190,
  "Handwerkskammer":200,
  "Finanzamt":210,
  "Arbeitsagentur":220,
  "Jobcenter":230,
  "Wirtschaftsförderung Landkreis / kreisfreie Stadt":240,
  "Förderbank Bund":260,
  "Förderbank Land":270,
  "Beteiligungsgesellschaft Land":280,
  "Bürgschaftsbank Land":290
}
