
module.exports = {
  "Bank":1,
  "Steuerberater":2,
  "Rechtsanwalt":3,
  "Krankenkasse ":4,
  "Unternehmensberater":5,
  "Marketingagentur":6,
  "Bürodienstleister":7,
  "Personaldienstleister":8,
  "Versicherungsmakler":9,
  "Finanzmakler":10,
  "Immobilienmakler":11,
  "IT-Dienstleister":12,
  "Krisenmanagement":13,
  "Einkaufsverbände":14,
  "Gebäudereinigung":15,
  "Energieberater":16,
  "Gemeindeverwaltung":17,
  "Industrie- und Handelskammer":18,
  "Handwerkskammer":19,
  "Finanzamt":20,
  "Arbeitsamt":21,
  "Jobcenter":22,
  "Wirtschaftsförderung Landkreis":23,
  "Wirtschaftsförderung Stadt":24,
  "Förderbank Bund":25,
  "Förderbank Land":26
}  
