#! /bin/bash

curl -XDELETE "$1/datenplaetze"
curl -XDELETE "$1/orte"

#
# Datenplatz
#

curl -XPUT "$1/datenplaetze"

curl -XPUT "$1/datenplaetze/datenplatz/_mapping" -d'
{
  "datenplatz": {
    "_source": {"enabled": "true"},
    "properties": {
      "id": {          
        "type": "string",
        "store": "yes",
        "analyzer": "keyword"
      },        
      "name": {          
        "type": "string",
        "store": "yes",
        "analyzer": "german",
        "boost": 2.0
      },
      "anschrift1": {
        "type": "string",
        "store": "yes",
        "analyzer": "german"
      },
      "anschrift2": {
        "type": "string",
        "store": "yes",
        "analyzer": "german"
      },
      "anschrift3": {
        "type": "string",
        "store": "yes",
        "analyzer": "german"
      },
      "telefon": {
        "type": "string",
        "store": "yes",
        "index": "not_analyzed"
      },
      "fax": {
        "type": "string",
        "store": "yes",
        "index": "not_analyzed"
      },
      "email": {
        "type": "string",
        "store": "yes",
        "index": "not_analyzed"
      },
      "url": {
        "type": "string",
        "store": "yes",
        "index": "not_analyzed"
      },
      "ort": {
        "type": "string",
        "store": "yes",
        "index": "not_analyzed"
      },
      "kategorie": {
        "type": "string",
        "store": "yes",
        "index": "not_analyzed"
      },
      "prio": {
        "type": "integer",
        "store": "yes"
      }
    }
  }
}'

#
# Ort
#

curl -XPUT "$1/orte"

curl -XPUT "$1/orte/ort/_mapping" -d'
{
  "ort": {
    "_source": {
      "enabled": "false"
    },
    "properties": {
        "id": {          
          "type": "string",
          "store": "yes",
          "analyzer": "keyword"
        },
        "bezeichnung": {
            "type": "completion",
            "index_analyzer": "whitespace",
            "search_analyzer": "whitespace",
            "payloads": "true"
        },
        "plz": {          
          "type": "string",
          "store": "yes",
          "analyzer": "keyword"
        },
        "land": {          
          "type": "string",
          "store": "yes",
          "analyzer": "keyword"
        },
        "gemeinde": {          
          "type": "string",
          "store": "yes",
          "analyzer": "keyword"
        },
        "koordinaten": {          
          "type": "geo_point",
          "store": "yes",
          "geohash": "true",
          "geohash_precision": "1km"
        }      
    }
  }
}'
